# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=120)),
                ('precio', models.IntegerField()),
                ('preciodecompra', models.IntegerField(default=0, verbose_name='precio de compra')),
                ('eliminado', models.BooleanField(default=False)),
                ('cantidadenexistencia', models.IntegerField(default=0, verbose_name='cantidad en existencia')),
            ],
        ),
    ]
