# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-30 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20180628_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
