# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numerodedocumento',
            field=models.CharField(max_length=120, unique=True, verbose_name='Numero de documento'),
        ),
    ]
